### ISSUE TITLE
RES1D_INSTALLATION & QGIS 3.24

### ISSUE THREAD

**Issue by ARTCON2020** [DHI/qgis-res1d-plugin#6]
Here is the problem where I couldn't interpret it
=====================================
Couldn't load plugin 'plugin' due to an error when calling its classFactory() method
ImportError: cannot import name 'find_stack_level' from 'pandas.util._exceptions' (C:\OSGeo4W\apps\Python39\lib\site-packages\pandas\util\_exceptions.py)
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/azmtas01/AppData/Roaming/QGIS/QGIS3\profiles\Tassew/python/plugins\plugin\__init__.py", line 15, in classFactory
    from .res1d_loader import Res1D
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/azmtas01/AppData/Roaming/QGIS/QGIS3\profiles\Tassew/python/plugins\plugin\res1d_loader.py", line 19, in 
    from .res1d_loader_dialog import Res1DDialog
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/azmtas01/AppData/Roaming/QGIS/QGIS3\profiles\Tassew/python/plugins\plugin\res1d_loader_dialog.py", line 27, in 
    from mikeio1d.res1d import Res1D
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\azmtas01\AppData\Roaming\Python\Python39\site-packages\mikeio1d\res1d.py", line 3, in 
    import pandas as pd
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\pandas\__init__.py", line 52, in 
    from pandas.core.api import (
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\pandas\core\api.py", line 14, in 
    from pandas.core.algorithms import factorize, unique, value_counts
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\pandas\core\algorithms.py", line 58, in 
    from pandas.core.indexers import validate_indices
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\pandas\core\indexers\__init__.py", line 1, in 
    from pandas.core.indexers.utils import (
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\pandas\core\indexers\utils.py", line 18, in 
    from pandas.util._exceptions import find_stack_level
ImportError: cannot import name 'find_stack_level' from 'pandas.util._exceptions' (C:\OSGeo4W\apps\Python39\lib\site-packages\pandas\util\_exceptions.py)

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
QGIS version: 3.24.0-Tisler Tisler, 6b44a42058

Python Path:
C:/OSGeo4W/apps/qgis/./python
C:/Users/azmtas01/AppData/Roaming/QGIS/QGIS3\profiles\Tassew/python
C:/Users/azmtas01/AppData/Roaming/QGIS/QGIS3\profiles\Tassew/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\Users\azmtas01\AppData\Roaming\Python\Python39\site-packages
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
C:\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/azmtas01/AppData/Roaming/QGIS/QGIS3\profiles\Tassew/python
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
C:\Users\azmtas01\AppData\Roaming\Python\Python39\site-packages\mikeio1d\bin
D:/QGIS

**Comment by ARTCON2020** [comment]
[QGIS3.24.pdf](https://github.com/DHI/qgis-res1d-plugin/files/8215093/QGIS3.24.pdf)
